### PR TITLE
feat(stats): Most used Languages size

### PR DESCRIPTION
**Pull request by abdulsalam0**
Modified the Size of the languages state to have the same size as the GitHub states

### CODE REVIEW

**Comment by orama254** [comment]
This is super awesome @abdulsalam0 

Are you participating in Hacktoberfest so that I can Accept it as an entry?

**Comment by abdulsalam0** [comment]
I am not 😞 but I want to take part

**Comment by orama254** [comment]
you can always sign up with your GitHub...just google hacktoberfest and sign up with your GitHub account

If you are ready I can approve and accept it for hacktoberfest  

@abdulsalam0

**Comment by abdulsalam0** [comment]
I am ready now thanks for telling me about it. 
@orama254

**Pull request merged**
